CREATE DATABASE BANCO_AWARI;

USE BANCO_AWARI;


CREATE TABLE BANCO_AWARI.CLIENTE (
	ID_CLIENTE BIGINT auto_increment NOT NULL,
	NOME varchar(100) NOT NULL,
	EMAIL varchar(100) NOT NULL,
	DOCUMENTO varchar(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	PRIMARY KEY(ID_CLIENTE)
);


-- CREATE

INSERT INTO CLIENTE  (NOME , EMAIL , DOCUMENTO , DATA_NASCIMENTO) 
	VALUES ('LUIZ DE ARAGAO', 'LUIZ@AWARI.COM', '987654321-10', '1989-07-30');

-- READ
SELECT * FROM CLIENTE;

-- UPDATE 
UPDATE CLIENTE SET DOCUMENTO = '485.014.130-70' WHERE ID_CLIENTE = 1;

-- DELETE 
DELETE FROM CLIENTE  WHERE ID_CLIENTE  = 2;




CREATE TABLE BANCO_AWARI.CONTA_CLIENTE (
	ID_CONTA BIGINT auto_increment NOT NULL,
	ID_CLIENTE BIGINT NOT NULL,
	TIPO varchar(100) NOT NULL,
	SALDO FLOAT NOT NULL,
	PRIMARY KEY(ID_CONTA),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- CREATE

INSERT INTO CONTA_CLIENTE  (ID_CLIENTE, TIPO, SALDO) 
	VALUES (1, 'CR', 1000000.00);

-- READ
SELECT * FROM CONTA_CLIENTE ;

-- UPDATE 
UPDATE CONTA_CLIENTE  SET SALDO = 10000000.00  WHERE ID_CONTA = 1;

-- DELETE 
DELETE FROM CONTA_CLIENTE  WHERE ID_CONTA  = 2;

	
CREATE TABLE BANCO_AWARI.TRANSACOES (
	ID_TRANSACOES BIGINT auto_increment NOT NULL,
	ID_CONTA BIGINT NOT NULL,
	ID_BANCO_DESTINO BIGINT NOT NULL,
	CONTA_DESTINO BIGINT NOT NULL,
	TIPO varchar(100) NOT NULL,
	VALOR FLOAT NOT NULL,
	PRIMARY KEY(ID_TRANSACOES),
	FOREIGN KEY (ID_CONTA) REFERENCES CONTA_CLIENTE(ID_CONTA)
);



-- CREATE

INSERT INTO TRANSACOES  (ID_CONTA, ID_BANCO_DESTINO, CONTA_DESTINO, TIPO, VALOR) 
	VALUES (1, 301, 123, 'TED', 50000.00);

-- READ
SELECT * FROM TRANSACOES ;

-- UPDATE 
UPDATE TRANSACOES  SET TIPO = 'TIPO TRANSACAO'  WHERE ID_CONTA = 1;
UPDATE TRANSACOES  SET TIPO = 'TIPO TRANSACAO'  WHERE ID_TRANSACOES  = 1;



	

